# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        in_memory:
            memory: ~
                
        db_provider:
            entity:
                class: AppBundle\Entity\User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout_on_user_change: true
            anonymous: ~
            provider: db_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login

            logout:
                path: logout
                target: homepage
            
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~
        
        secured_area:
            logout_on_user_change: true

            form_login:
                csrf_token_generator: security.csrf.token_manager
            
            provider: db_provider